stages:
  data_cleaning:
    cmd: python -m src.data_cleaning
    deps:
    - data/raw/Music_Info.csv
    - src/data_cleaning.py
    outs:
    - data/processed/cleaned_music_data.csv


  transform_data:
    cmd: python -m src.content_based_filtering
    deps:
    - data/processed/cleaned_music_data.csv
    - src/content_based_filtering.py
    - src/data_cleaning.py
    outs:
    - data/processed/transformed_data.npz
    - transformer.joblib
    - models/nearest_neighbor.joblib
