stages:
  data_cleaning:
    cmd: python -m src.data_cleaning
    deps:
    - data/raw/Music_Info.csv
    - src/data_cleaning.py
    outs:
    - data/processed/cleaned_music_data.csv


  transform_data:
    cmd: python -m src.content_based_filtering
    deps:
    - data/processed/cleaned_music_data.csv
    - src/content_based_filtering.py
    - src/data_cleaning.py
    outs:
    - data/processed/transformed_data.npz
    - transformer.joblib
    - models/nearest_neighbor_cbf.joblib
  

  interaction_data:
    cmd: python -m src.collaborative_filtering
    deps:
    - data/raw/User_Listening_History.csv
    - src/collaborative_filtering.py
    - data/processed/cleaned_music_data.csv
    outs:
    - data/processed/track_ids.npy
    - data/processed/collab_filtered_data.csv
    - data/processed/interaction_matrix.npz

  transformed_filtered_data:
    cmd : python -m src.transform_filtered_data
    deps : 
    - src/transform_filtered_data.py
    - data/processed/collab_filtered_data.csv
    outs :
    - data/processed/transformed_hybrid_data.npz